#!/usr/bin/env python
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Grygorii Tertychnyi

"""set-up-layers"""

import argparse
import json
import logging
import subprocess
import pathlib

VERSION = "1.0.0"
LOGGER: logging.Logger = logging.getLogger(__name__)


def run_git(args: list, cwd: pathlib.Path = pathlib.Path.cwd(), check: bool = False):
    ctx = subprocess.run(
        ["git"] + args,
        cwd=cwd,
        check=check,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )

    LOGGER.debug("%s", f"{ctx.stdout.decode().rstrip()}")
    LOGGER.debug(" => %d [%s]", ctx.returncode, " ".join(ctx.args))

    return ctx


def parse_args():
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description=f"{__doc__} {VERSION}",
    )

    parser.add_argument(
        "platform",
        help='platform name, for example "butterfly"',
    )

    parser.add_argument(
        "-m",
        "--manifest-filename",
        help="manifest filename",
        default="latest",
        metavar="JSON",
    )

    parser.add_argument(
        "-d",
        "--layers-dir",
        help="target layers directory",
        metavar="DIR",
        default=pathlib.Path(__file__).resolve().parent.parent.joinpath("layers"),
    )

    return parser.parse_args()


def main():
    args = parse_args()

    LOGGER.debug("%s", args)

    platform_name = args.platform

    manifest_filename = (
        pathlib.Path(__file__)
        .resolve()
        .parent.parent.joinpath(
            "manifests", platform_name, f"{args.manifest_filename}.json"
        )
        .resolve()
    )

    layers_dir = pathlib.Path(args.layers_dir).resolve()

    LOGGER.debug("manifest filename: %s", manifest_filename)
    LOGGER.debug("layers directory: %s", layers_dir)

    with open(manifest_filename, "r") as fil:
        m = json.load(fil)

    assert "projects" in m, f"manifest file {manifest} does not contain 'projects'"

    LOGGER.debug("projects: \n%s", json.dumps(m["projects"], indent=4))

    for p in m["projects"]:
        LOGGER.debug(" ::: setting up %s...", p["path"])

        ctx = run_git(["clone", "--origin", p["remote"], p["url"], p["path"]])
        assert ctx.returncode == 0, f"{p['path']}: failed to clone git repo"

        ctx = run_git(
            ["checkout", "-b", "wip/head", f"{p['remote']}/{p['revision']}"],
            cwd=p["path"],
        )
        assert ctx.returncode == 0, f"{p['path']}: failed to checkout {p['revision']}"

        ctx = run_git(
            ["branch", "--set-upstream-to", f"{p['remote']}/{p['upstream']}"],
            cwd=p["path"],
        )
        assert (
            ctx.returncode == 0
        ), f"{p['path']}: failed to set the upstream to {p['upstream']}"

    with open(layers_dir.parent.joinpath("bitbake-env"), "w") as bbenv:
        with open(layers_dir.parent.joinpath("scripts", "bitbake-env.template"), "r") as fil:
            for lin in fil.readlines():
                bbenv.write(lin.replace("@@MANIFEST_PLATFORM@@", platform_name))

    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::")
    print(" next step: source build environment to build images:")
    print("                                                     ")
    print(f" . {layers_dir.parent}/bitbake-env                  ")
    print("                                                     ")
    print(":::::::::::::::::::::::::::::::::::::::::::::::::::::")

if __name__ == "__main__":
    formatter = logging.Formatter(
        "::: %(asctime)s [%(levelname)8s] (%(name)s:%(lineno)s::%(funcName)s) %(message)s"
    )

    handler = logging.StreamHandler()
    handler.setLevel(logging.DEBUG)
    handler.setFormatter(formatter)

    LOGGER = logging.getLogger("setup-layers")
    LOGGER.setLevel(logging.DEBUG)
    LOGGER.addHandler(handler)

    main()
